export const projects = [
  {
    name: 'Join',
    desc: 'Create and organize tasks using drag and drop functions, assign users and categories.',
    technics: 'Html | Css | Javascript',
    img: 'assets/img/portfolio/join.png',
    link: 'https://join.martinklimt.de/',
    github: 'https://github.com/KnusperInge/Join',
    ready: true,
  },
  {
    name: 'Pollo Loco',
    desc: 'a simple Browsergame with Pepe',
    technics: 'Html | Css | Javascript',
    img: 'assets/img/portfolio/polloloco.png',
    link: 'https://polloloco.martinklimt.de/',
    github: 'https://github.com/KnusperInge/PolloLoco/',
    ready: true,
  },
  {
    name: 'Movielibrary',
    desc: 'a small private film library to have an overview of my own films and series.',
    technics: 'Angular | Firebase | Api',
    img: 'assets/img/portfolio/movielibrary.png',
    link: 'https://movielibrary.martinklimt.de',
    github: 'https://github.com/KnusperInge/Movie_Library',
    ready: true,
  },
  {
    name: 'Portfolio',
    desc: 'my own Portfolio',
    technics: 'Angular | Material Design',
    img: 'assets/img/portfolio/portfolio.png',
    link: '',
    github: '',
    ready: true,
  },
  {
    name: 'Kanban Backend',
    desc: 'a useful Kanban Backend with authentication',
    technics: 'Python |Django',
    img: 'assets/img/portfolio/py_django_placeholder.png',
    link: '',
    github: 'https://github.com/KnusperInge/Kanban_Backend',
    ready: true,
  },
];

export const skills = [
  'Html',
  'CSS',
  'Javascript',
  'Angular',
  'Rest-Api',
  'firebase',
  'Git',
  'Scrum',
];
